# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: People
    url: people
    weight: 30
  - name: Publications
    url: publication
    weight: 50
  - name: SCOAR
    url: https://hseo.whoi.edu/scoar-model/
    weight: 30
  - name: Projects
    url: https://hseo.whoi.edu/current-projects/
    weight: 40
  - name: Publications
    url: publication
    weight: 50
  - name: Teaching
    url: https://hseo.whoi.edu/teaching/
    weight: 60
  - name: Butterfly
    url: https://hseo.whoi.edu/butterfly-a-new-satellite-mission-concept/
    weight: 70
  - name: UCAO
    url: https://www.soest.hawaii.edu/oceanography/uc-ao/
    weight: 80